# Generated by Django 3.2 on 2022-06-30 13:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContactNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='Address',
            field=models.TextField(max_length=200, unique=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ContactNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Contact No'),
        ),
    ]
