# Generated by Django 3.2 on 2022-07-03 07:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20220630_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ContactNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact No'),
        ),
    ]
