# Generated by Django 3.2 on 2022-06-28 12:06

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('Make', models.CharField(max_length=50)),
                ('Part_Code', models.CharField(max_length=100)),
                ('Serial_Number', models.TextField(primary_key=True, serialize=False)),
                ('Item', models.CharField(max_length=50)),
                ('Location', models.TextField()),
                ('Purchase_Date', models.DateField()),
                ('Item_dispatched_Date', models.DateField()),
                ('Orgnization_Id', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=50)),
                ('Slip', models.FileField(upload_to='documents/%Y/%m/%d', validators=[inventory.validators.validate_file_extension])),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
    ]
