# Generated by Django 3.2 on 2022-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Status',
            field=models.IntegerField(choices=[('Working', 0), ('Not Working', 1)]),
        ),
    ]
