# Generated by Django 3.2 on 2022-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Working'), (1, 'Not Working')]),
        ),
    ]
