# Generated by Django 3.2 on 2022-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Status',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=20, null=True),
        ),
    ]
