# Generated by Django 3.2 on 2022-06-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Status',
        ),
    ]
