# Generated by Django 3.2 on 2022-06-28 14:57

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20220628_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='Slip',
            field=models.FileField(default='hgb', upload_to='', validators=[inventory.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
