# Generated by Django 3.2 on 2022-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20220703_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='Orgnization_Id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='OrgID',
            field=models.TextField(null=True),
        ),
    ]
