# Generated by Django 3.2 on 2022-07-03 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_ticket_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='DateCreated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
